server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: employee-service
          uri: http://localhost:8081
          predicates:
            - Path=/employees/**
          filters:
            - RemoveRequestHeader=Cookie
          metadata:
            roles: [admin]

        - id: certificate-service
          uri: http://localhost:8082
          predicates:
            - Path=/certificates/**
          filters:
            - RemoveRequestHeader=Cookie
          metadata:
            roles: [admin, user]

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: certiflow-client
            client-secret: ""
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/Certiflow

      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Certiflow
